source 'https://rubygems.org'

gem 'rack','2.2.3', :path => "vendor/gems/rack-2.2.3"
gem 'eventmachine','1.2.7', :path => "vendor/gems/eventmachine-1.2.7"
gem 'daemons','1.3.1', :path => "vendor/gems/daemons-1.3.1"
gem 'thin','1.7.2', :path => "vendor/gems/thin-1.7.2"
